# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under centrica_mlops_demo/resources/*
# and centrica_mlops_demo/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for centrica_mlops_demo Prod

on:
  push:
    tags: [ 'release*','v*.']
  workflow_dispatch:

defaults:
  run:
    working-directory: ./centrica_mlops_demo

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  prod:
    concurrency: centrica_mlops_demo-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.212.2
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
